### PR TITLE
Added cisco_nxos_show_banner_motd

### PR DESCRIPTION
**Pull request by GGabriele**
Added cisco_nxos_show_banner_motd

### CODE REVIEW

**Comment by jedelman8** [comment]
Can you try this on more complex and multi-line banners?

**Comment by GGabriele** [comment]
I tested the template against multi-line banners but I'm experiencing a problem: I tried to match the '\n' in many ways but it doesn't work how it should. I tried to collect it as a list but this is not a feasable solution. Anyone who have worked on a similar problem before?

**Comment by jedelman8** [comment]
What happened when you tried as a list?

**Comment by GGabriele** [comment]
I obtain this if I try it against ntc-ansible:

    {"changed": false, "response": [{"banner": ["User Access Verification", "DISCONNECT FROM DEVICE IMMEDIATELY.", "IF YOU CONTINUE, YOU WILL BE PROSECUTED TO THE FULLEST", "EXTENT OF THE LAW!!!"]}]}

...each line is a different value inside the list...right now, in order to make the it work I should define a parsed_sample with a fragmented banner

**Pull request closed without merging**
