### PR TITLE
Added cisco_nxos_show_snmp_community

### PR DESCRIPTION
**Pull request by GGabriele**
Added cisco_nxos_show_snmp_community

### CODE REVIEW

**Comment by jedelman8** [comment]
Did you test  with any contexts?  Any reason you didn't use \w for the acl filter?

**Comment by GGabriele** [comment]
I don't know the context format since they were not configured into tested devices and I have found no other example on the net.

Acl filter: I don't know what is the format (are "-" and other special characters accepted? If not, I modify this) so I choose .* instead of \w.

**Comment by jedelman8** [comment]
Understood...feel free to configure a filter to see what the accepted values :)

**Comment by GGabriele** [comment]
I'm having some problem in parsing multiple field lines with some missing values...I'm trying to parse this output:

    Community            Group / Access      context    acl_filter
    ---------            --------------      -------    ----------
    Community_test-1      network-operator    C0n_text!  T3st-ACL#$
    WEWORK                network-operator
    RW                    network-admin       _C0n
    networktocode         network-operator               
    YANKS                 network-admin                  my_acl

Obtaining:

    FSM Table:
    ['COMMUNITY', 'GROUP_ACCESS', 'CONTEXT', 'ACL_FILTER']
    ['Community_test-1', 'network-operator', 'C0n_text!', 'T3st-ACL#$']
    ['WEWORK', 'network-operator', '', '']
    ['RW', 'network-admin', '', '_C0n']
    ['networktocode', 'network-operator', '', '']
    ['YANKS', 'network-admin', '', 'my_acl']

I'm not succeeding in parsing the rigth Context/Acl_filter when acl_filter is missing

**Comment by jedelman8** [comment]
Okay, no problem.  Regarding my previous email (just now), don't include this one in the "master" index file then...will take a look at this soon too.

**Pull request closed without merging**
