### PR TITLE
ntc_show_command: argument_spec enhancement

### PR DESCRIPTION
**Pull request by sumkincpp**
Avoids emitting warning in Ansible 2.8 when argument_spec conversion happens.

### CODE REVIEW

**Review by jmcgill298 — CHANGES_REQUESTED** [review]
I would not like to add defaults to the module spec. Taking a quick look through the module, I can see that it probably needs to validate platform is not None and raise an appropriate error if it is. delay and global_delay should be left up to Netmiko, which I believe that is how it is currently working. trigger_device_list should be fine with None also.

**Comment by sumkincpp** [comment]
- Made `platform` required. If it's not passed from ansible, then module will emit error. Is it ok?
- `delay ` and `global_delay` in master branch have defaults of 1, should I introduce new behaviour here?
- I've left `trigger_device_list` as it was. I see that there might be some minor problems that different usage between host/trigger_device_list earlier introduced.. Should not be easier to make more strong specification and work with one parameter which might be list(many hosts) or string(one host)?

**Comment by jmcgill298** [comment]
```Made platform required. If it's not passed from ansible, then module will emit error. Is it ok?```
This can not be made required because it is one of the options made available to `provider`, which is why we have it as part of the `argument_check` section.

I think everything else looks okay

**Comment by jeffkala** [comment]
Should be closed and retested after #268 is merged.

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.

**Pull request closed without merging**
