### PR TITLE
show ip route support for cisco nexus switches

### PR DESCRIPTION
**Pull request by mzbenami**
I don't think this should be merged yet.

This PR:

* adds "show ip route" template for cisco_nxos devices (and it might work for cisco_ios as well)
* begins to phase out "vendor" to use "device_type" only

We should merge this after we agree on the strategy for vendor vs. device_type

### CODE REVIEW

**Comment by jedelman8** [comment]
Don't see the template here.

**Comment by mzbenami** [comment]
sorry, should be there now

**Comment by ubajze** [comment]
Hello

I tried the template on two "complex" IOS routing tables, but it does not work. 

##############
ansible:~/Temp/textfsmTemplates$ python ../textfsm-0.2.1/textfsm.py cisco_show_ip_route_alt sample_data/cisco_show_ip_route_1
FSM Template:
Value Filldown PREFIX (\d+\.\d+\.\d+\.\d+)
Value Filldown MASK (\d+)
Value NEXT_HOP (\d+\.\d+\.\d+\.\d+)
Value INTERFACE ([^\[]\S+/?\S+[^\]])
Value COST (\d\/\d)
Value TYPE (\w+)

Start
  ^\s*${PREFIX}/${MASK}, \S+: \S+ -> NewPrefix

NewPrefix
  ^\s+\*+via ${NEXT_HOP}, ${INTERFACE}, \[$COST\], \S+, ${TYPE} -> Record
  ^\s+\*+via ${NEXT_HOP}, \[$COST\], \S+, ${TYPE} -> Record
  ^.*(?!via).* -> Start

EOF


FSM Table:
['PREFIX', 'MASK', 'NEXT_HOP', 'INTERFACE', 'COST', 'TYPE']
ansible:~/Temp/textfsmTemplates$
##############

Maybe I can share my own implementation. (https://github.com/ubajze/textfsm_templates)

PS: Cisco should make these tables more "parsable" friendly. :)

**Comment by mzbenami** [comment]
Thanks ubajze,

The template was made for NXOS devices, though admittedly hasn't been tested for various levels of complexity. For example, multiple VRFs aren't accounted for yet.
Do you have access to NXOS devices with "complex" routing tables you can test on?
Has your implementation been tested on NXOS?

Thanks,
Michael

**Comment by jedelman8** [comment]
Uros, what platforms have you tested on?  Not sure if you've done the latest pull from the repo, but the template should match the OS too, i.e. cisco_ios, cisco_nxos, etc.  We can definitely use your contributions :)

**Comment by ubajze** [comment]
Hello

I tested my template on Cisco IOS platform in my virtual lab. I tried to create as complex routing table as possible to catch all cases. Currently the template works for my two cases, which I think it is a good approximation to the "complex" Cisco IOS routing table. I will create another branch and push my templates to repo, if you agree with that.

Unfortunately I don't have the access to the NXOS platform. But if you can provide some outputs, I can help with the templates. 

PS: I have a similar idea in the past to create some sort of REST API for network device output processing for different platforms. But for now, due to lack of time, I just created a simple framework with tests and some other features, which needs a lot of work to be "finished". :)

BR,

Uros

**Comment by jedelman8** [comment]
Thanks.  Definitely, please open a separate PR for the cisco_ios_show_ip_route template.  Curious to hear more about the REST API idea you have...this project is trying to take of some of that.  
Thank you!

**Comment by ubajze** [comment]
My idea was to create an public/private API, which will allow users to post their output from the different type of network devices (ex. show ip route). The API will then process their output and return parsed output, for example in JSON format. In this way you can have different outputs from different vendors, but the output of the API will always be in the same format. It is some sort of abstraction layer. I know it is not a new idea, but I started it, as my hobby project :)

The idea was to use some sort of python web framework, like Flask or Django. I already started doing some initial coding, but then leave it due to lack of time and maybe to develop idea a little bit more :)

**Comment by mzbenami** [comment]
updated nxos_show_ip_route template for complex routing tables

**Pull request merged**
