### PR TITLE
Changes to permit proxycommand on ntc_show_command

### PR DESCRIPTION
**Pull request by iamroddo**
Add lines to allow ntc_show_command to work with proxycommand by adding ssh_config_file and setting it to ~/.ssh/config by default.

### CODE REVIEW

**Comment by jmcgill298** [comment]
@iamroddo @optiz0r @dmitrijsf does this not work by using connection args? From the examples in the docstring:
```
# USING BASTION HOST WITH NETMIKO
  - ntc_show_command:
      connection: netmiko_ssh
      platform: arista_eos
      command: show ip interface brief
      template_dir: '/home/ntc/ntc-templates/templates'
      host: "{{inventory_hostname}}"
      username: "{{ username }}"
      password: "{{ password }}"
      connection_args:
        ssh_config_file: '/home/ntc/playbook/ssh_config'
```

**Review by jmcgill298 — CHANGES_REQUESTED** [review]
This functionality should be provided by `connectiong_args`

**Comment by jeffkala** [comment]
Should be closed and retested after #268 is merged.

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.

**Pull request closed without merging**
