### PR TITLE
Added cisco_ios_show_access-list

### PR DESCRIPTION
**Pull request by GGabriele**
Added cisco_ios_show_access-list. I'm experiencing strange behaviours when I test it with ntc-ansible. It doesn't give back errors but it doesn't load parsed_sample. Please review it.

### CODE REVIEW

**Comment by bedecarroll** [comment]
Hi @GGabriele I just loaded up your diff then and was able to run the test-template against it successfully:

```
PLAY RECAP ********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```

Are you sure it isn't loading your parsed file? I see ```'ansible_facts': {'parsed_sample':``` when I look at the verify task. My run was against the current master after a git apply of your changes.

Hope that helps!

**Comment by GGabriele** [comment]
Thanks @bedecarroll ! Maybe I had some strange configuration on my virtual environment.
Thanks for your help.

**Comment by jedelman8** [comment]
I think you may have forgot the raw file :)  can you update and include it?  Which is odd because the checks are passing.  Will need to look into this.

**Comment by GGabriele** [comment]
I added the .raw file :) Please test it. It returns this error in my environment:

    msg: {'protocol': 'igmp', 'option': '', 'destination': 'host 1.1.1.1', 'source': 'any', 'sn': '10', 'action': 'permit', 'modifier': '', 'id': 'Virtual-Access1.1#1'} is not found in sample input

While here it is the parsed_sample field:
    
    failed: [localhost] => *omitted output* [{u'protocol': u'igmp', u'option': u'', u'destination': u'host 1.1.1.1', u'source': u'any', u'sn': u'10', u'action': u'permit', u'modifier': u'', u'id': u'Virtual-Access1.1#1'}

**Pull request closed without merging**
