### PR TITLE
Added arista_eos_show_mac_address-table

### PR DESCRIPTION
**Pull request by GGabriele**
Added arista_eos_show_mac_address-table.

Multicast Addresses associated to more than 10 ports break the output into multiple lines. I don't know if this solution may works or if we better wait to implement multiple line handling. Plese review this.

### CODE REVIEW

**Comment by jedelman8** [comment]
Can you just add a comment in the template to state this?

**Comment by GGabriele** [comment]
Done :)

**Comment by GGabriele** [comment]
If you want I can close and reopen this to avoid conflicts.

**Comment by jedelman8** [comment]
You shouldn't need to close / re-open, but just get the updated index file in this PR.  Whatever is easier for you.

**Pull request closed without merging**
