### PR TITLE
BugFix: Update "provider" to work with Ansible2.8

### PR DESCRIPTION
**Pull request by jmcgill298**

### CODE REVIEW

**Comment by jmcgill298** [comment]
@FragmentedPacket You can update this branch

**Comment by jmcgill298** [comment]
Fixes #244

**Comment by FragmentedPacket** [comment]
@jmcgill298 Updates have been pushed up.

**Comment by FragmentedPacket** [comment]
@jmcgill298 Took care of this and just handled it with `module.fail_json`

**Pull request merged**
