### PR TITLE
Added cisco_nxos_show_access-lists

### PR DESCRIPTION
**Pull request by GGabriele**
Template should be okay but it returns some parsing errors. I'm PRing anyway because I want to test it with Travis

### CODE REVIEW

**Comment by GGabriele** [comment]
Okay, I fixed the errors.

I've tested this with lots of different configurations. At this point it doesn't support only UDF match (User Defined Field) due to its different structure.

**Comment by jedelman8** [comment]
Just to confirm, this is good to go?

**Comment by GGabriele** [comment]
It is, but as I said it does not support user defined field.

**Comment by jedelman8** [comment]
Okay, no prob.  For the complex ones and caveats, we can start to include comments like this:

https://github.com/networktocode/ntc-ansible/blob/master/ntc_templates/cisco_ios_show_ip_bgp.template

Can you include a comment in the template and we'll get this one merged?

**Comment by GGabriele** [comment]
Okay, I added some comments

**Pull request merged**
