### PR TITLE
Add ability to escalate show command privileges

### PR DESCRIPTION
**Pull request by tcuthbert**
This feature implements the ability to escalate the show command session privileges.

### CODE REVIEW

**Comment by jedelman8** [comment]
Why is this needed for `show` commands?

**Comment by tcuthbert** [comment]
We are an msp. We dont always have aaa setup for accts to login straight to
privilege 15.

**Comment by jtdub** [comment]
Can you give an example of a show command that needs escalated privileges? The only thing I can think of is doing something like 'show run', in which case I would ask what's in show run that you can't get from a specific show command, such as show interface, etc.?

**Comment by tcuthbert** [comment]
I'm trying to cycle SNMP keys but require enable mode to get what currently exists

## Getting SNMP community from CSR
show snmp community ?
% Unrecognized command

Cisco IOS XE Software, Version 03.15.00.S - Standard Support Release
Cisco IOS Software, CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 15.5(2)S, RELEASE SOFTWARE (fc3)

## Getting snmp community from Cisco 6500
show snmp community?
% Unrecognized command
sh ver
Cisco IOS Software, C3560E Software (C3560E-UNIVERSALK9-M), Version 12.2(55)SE3, RELEASE SOFTWARE (fc1)

**Pull request merged**
