### PR TITLE
add no_log=True to password field

### PR DESCRIPTION
**Pull request by bobthebutcher**

### CODE REVIEW

**Comment by bobthebutcher** [comment]
Without this argument passwords are displayed in plain text when using the -vvv verbosity level

**Comment by GGabriele** [comment]
@bobthebutcher thank you for this!
Can you please rebase this PR to solve conflicts?

**Comment by bobthebutcher** [comment]
Done. Thanks for reviewing!

**Comment by GGabriele** [comment]
Thank you for contributing!

**Pull request merged**
