### PR TITLE
add nxos_show_ip_ospf_neighbor_vrf

### PR DESCRIPTION
**Pull request by jtdub**
This command allows you to get the OSPF neighbor relationships of any specific vrf or ALL of them. To obtain this flexibility, I had use regex in the ntc_templates/index file:

```
cisco_nxos_show_ip_ospf_neighbor_vrf.template, .*, cisco_nxos, sh[[ow]] ip ospf nei[[ghbor]] vrf (\S+)
```
It passes the test-templates.py script. :+1:

### CODE REVIEW

**Comment by jtdub** [comment]
I also used the textfsm filldown and required features, which worked well in the template.

**Comment by jedelman8** [comment]
Would you mind updating this real fast with the latest index file?  It'll make it so I don't have to do a manual merge.  Having the index file always being changing with multiple templates getting added kind of stinks :)

**Comment by jedelman8** [comment]
Want to test trying to get states other than FULL?  Your call :)

**Comment by jtdub** [comment]
Standby.

**Comment by jtdub** [comment]
Derp. I accidently squashed somebody elses snmp tests.

**Pull request merged**
