### PR TITLE
adding ios sh ver

### PR DESCRIPTION
**Pull request by jtdub**
Adding ios show version

### CODE REVIEW

**Comment by jedelman8** [comment]
Ahh, this is where we should probably at a minimum standardize on data returned for ios, nxos, and eos.  What do you think?  I don't mind helping here...just not today :)

**Comment by jtdub** [comment]
Yes. I agree. Should we put together a document of standard variable names and the standard items to get for common commands?

**Comment by jedelman8** [comment]
We could, but for now, I was thinking just do all 3 for 'show version' and take it one command at a time from here.  show version is just one of those commands that should have been done already...I thought it was, but only nxos.  Maybe in a few weeks time, take a step back and standardize on var names, and document that, etc.

**Comment by jedelman8** [comment]
Merging for now, will re-visit soon to streamline var names in each.

**Pull request merged**
