### PR TITLE
Ios vtp status

### PR DESCRIPTION
**Pull request by jtdub**
added ios vtp status, ios ospf neighbors, ios standby brief, and nxos port-channel sum

### CODE REVIEW

**Comment by jtdub** [comment]
Since I was fixing PR's to work with the new tests directory structure / travis-ci, I merged my three existing PR's (vtp status, sh ip ospf neighbors, and sh standby brief) into a single PR.

**Comment by jtdub** [comment]
merged the nxos show port channel summary as well.

**Comment by jedelman8** [comment]
Thanks!  I was going to make these changes today for you actually...thanks for making them!

What are you using the group_vars for?

**Comment by jtdub** [comment]
I'm not currently using them. I was trying to be consistent with what was already in place. :)

**Pull request merged**
