### PR TITLE
Added cisco_show_interface_brief

### PR DESCRIPTION
**Pull request by GGabriele**
Added cisco_nxos_show_interface_brief

### CODE REVIEW

**Comment by jedelman8** [comment]
Would you mind redoing this using different TextFSM states for each section of the output?  It'll make the template easier to read.  Even if you match verbatim the section header and then go to the rules for that section.  There are some examples like this already, but you can see more here:
https://code.google.com/p/textfsm/wiki/TextFSMHowto

From the textfsm website (see below)...notice how it matches a line Routing Engine Status and then goes to RESlot.  I'm thinking you can have a few different "titles" defined per section of the output and then go to each one, then go back to Start.  Feel free to push back if you don't think this will work too :)  worth giving it a shot.

```
# Chassis value will be null for single chassis routers.
Value Filldown Chassis (.cc.?-re.)
Value Required Slot (\d+)
Value State (\w+)
Value Temp (\d+)
Value CPUTemp (\d+)
Value DRAM (\d+)
Value Model (\S+)

# Allway starts in 'Start' state.
Start
  ^${Chassis}
  # Record current values and change state.
  # No record will be output on first pass as 'Slot' is 'Required' but empty.
  ^Routing Engine status: -> Record RESlot

# A state transition was not strictly necessary but helpful for the example.
RESlot
  ^\s+Slot\s+${Slot}
  ^\s+Current state\s+${State}
  ^\s+Temperature\s+${Temp} degrees
  ^\s+CPU temperature\s+${CPUTemp} degrees
  ^\s+DRAM\s+${DRAM} MB
  # Transition back to Start state.
  ^\s+Model\s+${Model} -> Start

# An implicit EOF state outputs the last record.
```

**Comment by GGabriele** [comment]
Done! :)

**Comment by jedelman8** [comment]
Cool..this wasn't EXACTLY what I thinking...in this setup, what happens if you don't have any loopbacks or VLANs, or portchannels? 

I was thinking:

Start
  Title regex for Ethernet
  Title regex for loopback
  ...

Ethernet
  match, record, and go back to start


Make sense?  Let me know what you think.

**Comment by GGabriele** [comment]
Oh, you're right, this definitely makes sense.

I've modified the template to meet the requirements. Now it works :)

**Pull request merged**
